---

- name: Install Node.js (package)
  pkg:
    name: "{{ gie_proxy_nodejs_package }}"
  when: gie_proxy_setup_nodejs == "package"

- name: Install Node.js (nodeenv) Tasks
  block:

    - name: Install Nodeenv
      pip:
        name: nodeenv
        virtualenv: "{{ gie_proxy_virtualenv }}"
        virtualenv_command: "{{ gie_proxy_virtulenv_command |default(omit) }}"
        virtualenv_python: "{{ gie_proxy_virtulenv_python |default(omit) }}"

    - name: Install Node.js
      command: "nodeenv -p {{ ('-n ' ~ gie_proxy_nodejs_version) |default('') }}"
      args:
        creates: "{{ gie_proxy_virtualenv }}/bin/node"
      environment:
        PATH: "{{ gie_proxy_virtualenv }}/bin:{{ ansible_env.PATH }}"

  when: gie_proxy_setup_nodejs == "nodeenv"
